/*
  NOTE:
  This file is normally generated by Supabase CLI.
  In this repo we keep a hand-maintained minimal type surface
  matching the Phase 3/4/5 SQL in /supabase/sql.
*/

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  public: {
    Enums: {
      tenant_role: 'tech' | 'owner' | 'admin' | 'editor' | 'staff' | 'viewer'
    }
    Tables: {
      tenants: {
        Row: {
          id: string
          slug: string
          name: string
          plan: string
          status: string
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          slug: string
          name: string
          plan?: string
          status?: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          slug?: string
          name?: string
          plan?: string
          status?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      tenant_memberships: {
        Row: {
          tenant_id: string
          user_id: string
          role: Database['public']['Enums']['tenant_role']
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          user_id: string
          role?: Database['public']['Enums']['tenant_role']
          created_at?: string
          updated_at?: string
        }
        Update: {
          tenant_id?: string
          user_id?: string
          role?: Database['public']['Enums']['tenant_role']
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      audit_events: {
        Row: {
          id: string
          tenant_id: string
          actor_user_id: string | null
          action: string
          entity: string
          entity_id: string | null
          meta: Json
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          actor_user_id?: string | null
          action: string
          entity: string
          entity_id?: string | null
          meta?: Json
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          actor_user_id?: string | null
          action?: string
          entity?: string
          entity_id?: string | null
          meta?: Json
          created_at?: string
        }
        Relationships: []
      }
      
      ai_jobs: {
        Row: {
          id: string
          tenant_id: string
          requested_by: string | null
          scope: string
          kind: string
          input: Json
          status: string
          claimed_by: string | null
          claimed_at: string | null
          result: Json | null
          error: string | null
          idempotency_key: string | null
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          requested_by?: string | null
          scope?: string
          kind: string
          input?: Json
          status?: string
          claimed_by?: string | null
          claimed_at?: string | null
          result?: Json | null
          error?: string | null
          idempotency_key?: string | null
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          requested_by?: string | null
          scope?: string
          kind?: string
          input?: Json
          status?: string
          claimed_by?: string | null
          claimed_at?: string | null
          result?: Json | null
          error?: string | null
          idempotency_key?: string | null
          created_at?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'ai_jobs_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
      ai_audit_events: {
        Row: {
          id: string
          tenant_id: string
          actor_user_id: string | null
          action: string
          meta: Json
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          actor_user_id?: string | null
          action: string
          meta?: Json
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          actor_user_id?: string | null
          action?: string
          meta?: Json
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: 'ai_audit_events_tenant_id_fkey'
            columns: ['tenant_id']
            referencedRelation: 'tenants'
            referencedColumns: ['id']
          },
        ]
      }
tenant_credit_ledger: {
        Row: {
          id: string
          tenant_id: string
          actor_user_id: string | null
          delta: number
          reason: string
          ref: string | null
          meta: Json
          created_at: string
        }
        Insert: {
          id?: string
          tenant_id: string
          actor_user_id?: string | null
          delta: number
          reason: string
          ref?: string | null
          meta?: Json
          created_at?: string
        }
        Update: {
          id?: string
          tenant_id?: string
          actor_user_id?: string | null
          delta?: number
          reason?: string
          ref?: string | null
          meta?: Json
          created_at?: string
        }
        Relationships: []
      }
      stripe_customers: {
        Row: {
          tenant_id: string
          customer_id: string
          created_at: string
          updated_at: string
        }
        Insert: {
          tenant_id: string
          customer_id: string
          created_at?: string
          updated_at?: string
        }
        Update: {
          tenant_id?: string
          customer_id?: string
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      stripe_subscriptions: {
        Row: {
          subscription_id: string
          tenant_id: string
          status: string
          price_id: string | null
          current_period_end: string | null
          cancel_at_period_end: boolean
          created_at: string
          updated_at: string
        }
        Insert: {
          subscription_id: string
          tenant_id: string
          status: string
          price_id?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
        }
        Update: {
          subscription_id?: string
          tenant_id?: string
          status?: string
          price_id?: string | null
          current_period_end?: string | null
          cancel_at_period_end?: boolean
          created_at?: string
          updated_at?: string
        }
        Relationships: []
      }
      stripe_events: {
        Row: {
          event_id: string
          received_at: string
        }
        Insert: {
          event_id: string
          received_at?: string
        }
        Update: {
          event_id?: string
          received_at?: string
        }
        Relationships: []
      }
    }
    Views: {
      tenant_credit_balance: {
        Row: {
          tenant_id: string
          balance: number
        }
      }
    }
    Functions: {
      onboard_tenant: {
        Args: {
          p_user_id: string
          p_tenant_name: string
          p_plan?: string
        }
        Returns: string
      }
      charge_credits: {
        Args: {
          p_tenant_id: string
          p_amount: number
          p_reason: string
          p_ref?: string | null
          p_meta?: Json
        }
        Returns: { balance: number }[]
      }
      tenant_role: {
        Args: { p_tenant_id: string }
        Returns: Database['public']['Enums']['tenant_role']
      }
    }
    CompositeTypes: never
  }
}
